from ROOT import *
gJetsFile = TFile("inputs/allgJets_Jan29.root")
sideBandHisto = gJetsFile.Get("Resonance/phJetInvMassHist_pruned_sideLow")
#sideBandHisto = gJetsFile.Get("Resonance/phJetInvMassHist_pruned_sideHi")
sigRegHisto = gJetsFile.Get("Resonance/phJetInvMassHist_pruned_sig")
#sideBandHisto = gJetsFile.Get("Resonance/phJetInvMassHist_pruned_sideLow_noTrig")
##sideBandHisto = gJetsFile.Get("Resonance/phJetInvMassHist_pruned_sideHi_noTrig")
#sigRegHisto = gJetsFile.Get("Resonance/phJetInvMassHist_pruned_sig_noTrig")
ratio = sigRegHisto.Clone()
ratio.Sumw2()
ratio.Divide(sideBandHisto)
c1 = TCanvas("c1","c1",800,800)
ratio.Draw()
#ratio.Rebin()
ratio.SetMarkerStyle(20)
ratio.SetLineColor(kBlack)
for i in range (0, 10):
    ratio.Fit("pol1", "", "", 500, 1000)
gStyle.SetOptFit(1111)
c1.Update()
ratio.SetTitle("Ratio: events in signal region to events n lower sideband region")
ratio.GetYaxis().SetTitle("n_{sig region}/n_{lower sideband}")
ratio.GetXaxis().SetTitle("m_{#gammaj} (GeV)")
ratio.GetXaxis().SetRangeUser(500,1000)
ratio.SetTitle("Ratio: events in signal region to events n lower sideband region, gJets")
ratio.Draw("pE")
c1.Update()
print ratio.GetXaxis().GetBinWidth(10)
