from ROOT import *

inFile = TFile("allJetVars.root")

leadingJetTau1             = inFile.Get("leadingJetTau1Hist")
leadingJetTau2             = inFile.Get("leadingJetTau2Hist")
leadingJetTau3             = inFile.Get("leadingJetTau3Hist")
leadingJetT2T1             = inFile.Get("leadingJetT2T1")
leadingJetT3T2             = inFile.Get("leadingJetT3T2")
leadingJetMass             = inFile.Get("leadingJetMass")
leadingJetPrunedCorrMass   = inFile.Get("leadingJetPrunedCorrMass")
leadingJetSoftdropCorrMass = inFile.Get("leadingJetSoftdropCorrMass")
leadingPhMVAhist_barrel    = inFile.Get("leadingPhMVAhist_barrel")
leadingPhMVAhist_endcap    = inFile.Get("leadingPhMVAhist_endcap")

canvas1 = TCanvas("canvas1", "canvas1", 800, 800)
canvas2 = TCanvas("canvas2", "canvas2", 800, 800)
canvas3 = TCanvas("canvas3", "canvas3", 800, 800)
canvas4 = TCanvas("canvas4", "canvas4", 800, 800)
canvas5 = TCanvas("canvas5", "canvas5", 800, 800)
canvas6 = TCanvas("canvas6", "canvas6", 800, 800)
canvas7 = TCanvas("canvas7", "canvas7", 800, 800)

leadingJetTau1             .GetXaxis().SetTitle("Leading AK8 jet #tau_{1}")
leadingJetTau2             .GetXaxis().SetTitle("Leading AK8 jet #tau_{2}")
leadingJetTau3             .GetXaxis().SetTitle("Leading AK8 jet #tau_{3}")
leadingJetT2T1             .GetXaxis().SetTitle("Leading AK8 jet #tau_{2}/#tau_{1}")
leadingJetT3T2             .GetXaxis().SetTitle("Leading AK8 jet #tau_{3}/#tau_{2}")
leadingJetMass             .GetXaxis().SetTitle("leading AK8 jet mass [GeV]")
leadingJetPrunedCorrMass   .GetXaxis().SetTitle("leading AK8 pruned jet mass (corrected) [GeV]")
leadingJetSoftdropCorrMass .GetXaxis().SetTitle("leading AK8 softdrop jet mass (corrected) [GeV]")
leadingPhMVAhist_barrel    .GetXaxis().SetTitle("Barrel photon ID MVA value")
leadingPhMVAhist_endcap    .GetXaxis().SetTitle("Endcap photon ID MVA value")

leadingJetTau1             .GetYaxis().SetTitle("Events")
leadingJetTau2             .GetYaxis().SetTitle("Events")
leadingJetTau3             .GetYaxis().SetTitle("Events")
leadingJetT2T1             .GetYaxis().SetTitle("Events")
leadingJetT3T2             .GetYaxis().SetTitle("Events")
leadingJetMass             .GetYaxis().SetTitle("Events")
leadingJetPrunedCorrMass   .GetYaxis().SetTitle("Events")
leadingJetSoftdropCorrMass .GetYaxis().SetTitle("Events")
leadingPhMVAhist_barrel    .GetYaxis().SetTitle("Events")
leadingPhMVAhist_endcap    .GetYaxis().SetTitle("Events")

leadingJetTau1             .GetYaxis().SetLabelSize(0.025)
leadingJetTau2             .GetYaxis().SetLabelSize(0.025)
leadingJetTau3             .GetYaxis().SetLabelSize(0.025)
leadingJetT2T1             .GetYaxis().SetLabelSize(0.025)
leadingJetT3T2             .GetYaxis().SetLabelSize(0.025)
leadingJetMass             .GetYaxis().SetLabelSize(0.03)
leadingJetPrunedCorrMass   .GetYaxis().SetLabelSize(0.03)
leadingJetSoftdropCorrMass .GetYaxis().SetLabelSize(0.03)
leadingPhMVAhist_barrel    .GetYaxis().SetLabelSize(0.02)
leadingPhMVAhist_endcap    .GetYaxis().SetLabelSize(0.02)

leadingJetTau1             .GetYaxis().SetTitleOffset(1.3)
leadingJetTau2             .GetYaxis().SetTitleOffset(1.3)
leadingJetTau3             .GetYaxis().SetTitleOffset(1.3)
leadingJetT2T1             .GetYaxis().SetTitleOffset(1.3)
leadingJetT3T2             .GetYaxis().SetTitleOffset(1.3)
leadingJetMass             .GetYaxis().SetTitleOffset(1.2)
leadingJetPrunedCorrMass   .GetYaxis().SetTitleOffset(1.2)
leadingJetSoftdropCorrMass .GetYaxis().SetTitleOffset(1.2)
leadingPhMVAhist_barrel    .GetYaxis().SetTitleOffset(1.5)
leadingPhMVAhist_endcap    .GetYaxis().SetTitleOffset(1.5)


canvas1.cd()
leadingJetTau1.Draw()

canvas2.cd()
leadingJetTau2.Draw()

canvas3.cd()
leadingJetTau3.Draw()

canvas4.cd()
leadingJetT2T1.Draw()

canvas5.cd()
leadingJetT3T2.Draw()

canvas6.SetLogy()
canvas6.cd()
leadingJetPrunedCorrMass.GetXaxis().SetRangeUser(0,1000)
leadingJetPrunedCorrMass.Draw()
canvas6.Update()
prunedCorrMassStats = leadingJetPrunedCorrMass.FindObject("stats")
prunedCorrMassStats.SetTextColor(kBlue)
canvas6.Update()
leadingJetSoftdropCorrMass.SetLineColor(kRed)
leadingJetSoftdropCorrMass.Draw("SAMES")
canvas6.Update()
softDropCorrMassStats = leadingJetSoftdropCorrMass.FindObject("stats")
softDropCorrMassStats.SetX1NDC(0.778894)
softDropCorrMassStats.SetX2NDC(0.979899)
softDropCorrMassStats.SetY1NDC(0.600259)
softDropCorrMassStats.SetY2NDC(0.759379)
softDropCorrMassStats.SetTextColor(kRed)
canvas6.Update()
leadingJetMass.SetLineColor(kBlack)
leadingJetMass.Draw("SAMES")
canvas6.Update()
jetMassStats = leadingJetMass.FindObject("stats")
jetMassStats.SetX1NDC(0.561558)
jetMassStats.SetX2NDC(0.762563)
jetMassStats.SetY1NDC(0.776197)
jetMassStats.SetY2NDC(0.935317)
jetMassStats.SetTextColor(kBlack)
canvas6.Update()

canvas7.cd()
leadingPhMVAhist_barrel.Draw()
canvas7.Update()
barrelMVAstats = leadingPhMVAhist_barrel.FindObject("stats")
leadingPhMVAhist_endcap.Draw("SAMES")
canvas7.Update()
barrelMVAstats.SetTextColor(kBlue)
leadingPhMVAhist_endcap.SetLineColor(kRed)
endcapMVAstats = leadingPhMVAhist_endcap.FindObject("stats")
endcapMVAstats.SetX1NDC(0.775126)
endcapMVAstats.SetX2NDC(0.976131)
endcapMVAstats.SetY1NDC(0.600259)
endcapMVAstats.SetY2NDC(0.759379)
endcapMVAstats.SetTextColor(kRed)
canvas7.Update()

canvas1.Print(              "LeadingJetTau1.pdf" )
canvas2.Print(              "LeadingJetTau2.pdf" )
canvas3.Print(              "LeadingJetTau3.pdf" )
canvas4.Print(              "LeadingJetT2T1.pdf" )
canvas5.Print(              "LeadingJetT3T2.pdf" )
canvas6.Print( "JetMass_raw+softdrop+pruned.pdf" )
canvas7.Print(             "PhotonIDmvaVals.pdf" )

#if __name__ == '__main__':
#   rep = ''
#   while not rep in [ 'q', 'Q' ]:
#      rep = raw_input( 'enter "q" to quit: ' )
#      if 1 < len(rep):
#         rep = rep[0]
