from ROOT import *

infile = TFile("output_Z_sidebandside5070_masswindow500-2000/phJetInvMass_pruned_sig_canvas.root")
oldHist = infile.Get("sidebandOld")
newHist = infile.Get("sideband")
ratioHist = newHist.Clone()
ratioHist.GetYaxis().SetRangeUser(-1, 5)
ratioHist.Sumw2()
ratioHist.SetStats(0)
ratioHist.SetTitle("ratio: new #||{cos(#theta*)} cut / no cut, 50-70 sideband")
ratioHist.GetYaxis().SetTitle("Ratio of Events: new/old")
ratioHist.GetXaxis().SetTitle("m_{#gammaj}")
ratioHist.Divide(oldHist)

canvas = TCanvas()
canvas.cd()
ratioHist.SetMarkerStyle(20)
ratioHist.SetMarkerColor(kBlack)
ratioHist.SetLineColor(kBlack)
ratioHist.Draw("pE")
